# https://docs.microsoft.com/azure/devops/pipelines/languages/android
pool:
  vmImage: 'macOS-10.13'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

# Android Signing
# Sign and align Android APK files
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk' 
    apksign: true # Optional
    apksignerKeystoreFile: 'my.keystore'
    apksignerKeystorePassword: 'qwerty'
    apksignerKeystoreAlias: 'my'
    apksignerKeyPassword: 'qwerty'
    #apksignerArguments: '--verbose' # Optional
    #apksignerFile: # Optional
    #zipalign: true # Optional
    #zipalignFile: # Optional